name: Update Analyses & Sets

on:
  workflow_dispatch:
  schedule:
    - cron: '12 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build smogon
      run: npm build smogon
    - name: Update
      run: node update/sets
    - name: Test
      run: npm run test
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Analyses & Sets ($(date "+%Y-%m-%d"))" || exit 0
        git push
