name: Update Imgs

on:
  workflow_dispatch:
  schedule:
    - cron: '20 2 * * 1'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install --force
    - name: Update
      run: node --no-warnings --experimental-specifier-resolution=node update/imgs
    - name: Test
      run: npm run test
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Imgs ($(date "+%Y-%m-%d"))" || exit 0
        git push
